## 应用名称
#spring.application.name=spring-dynamic-mybatis
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.mrgao.demo.mybatis.entity
## 应用服务 WEB 访问端口
#server.port=8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    datasource1: #数据源1
      url:
      username:
      password:
      driver-class-name: org.postgresql.Driver
      druid:
        test-on-borrow: true
        initial-size: 1
        max-active: 20
        min-idle: 5
    datasource2: #数据源2
      url:
      username:
      password:
      driver-class-name: org.postgresql.Driver
      druid:
        test-on-borrow: true
        initial-size: 1
        max-active: 20
        min-idle: 5
